import { ApolloClient, InMemoryCache } from '@apollo/client'
import { GET_HOMEPAGE } from '../graphql/queries'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({homePage}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {homePage.Hero.Heading}
        </h1>

        <p className={styles.description}>
          {homePage.Hero.Subheading}
        </p>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const client = new ApolloClient({
    uri: process.env.STRAPI_GRAPHQL_API,
    cache: new InMemoryCache()
  });

  const { data } = await client.query({ query: GET_HOMEPAGE });
 
  return {
    props: {
      homePage: data.homepage.data.attributes
    }
  }
}
